application: alyssa-quek
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img/favicon\.ico
  static_files: img/favicon\.ico
  upload: img/favicon\.ico
  expiration: 30d

- url: /css
  static_dir: css
  expiration: 1d
  http_headers:
    Vary: Accept-Encoding

- url: /js
  static_dir: js

- url: /img
  expiration: 1d
  static_dir: img

- url: /.*
  script: webserver.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
